return {
    year    = "2027",
    classes = {
        {
            key   = "basic",
            name  = "Basic",
            reset = "2f7cd5",
            seq   = {
                {file="5ab88c", label="Immelmann"},
                {file="a87d7e", label="Vertical Downline"},
                {file="460043", label="Hammerhead"},
                {file="f6f356", label="Humpty Bump"},
                {file="705bd0", label="Half Cuban"},
                {file="7b2e8a", label="Laydown Humpty"},
                {file="3d4bae", label="Reverse Sharks Tooth"},
                {file="ceaecb", label="Loop"},
                {file="6bb17e", label="Vertical Upline"},
                {file="a1b162", label="Spin"},
            },
        },
        {
            key   = "sport",
            name  = "Sportsman",
            reset = "4afef4",
            seq   = {
                {file="8b308b", label="Q Loop"},
                {file="52d04f", label="Fig P"},
                {file="55a394", label="Hammer Head"},
                {file="77fcb7", label="Humpty"},
                {file="646afc", label="Loop"},
                {file="341a31", label="Tear Drop"},
                {file="dd2954", label="Reverse Sharks Tooth"},
                {file="8b6d37", label="Immelmann"},
                {file="123c53", label="Spin"},
                {file="1d04f3", label="Half Cuban"},
            },
        },
        {
            key   = "inter",
            name  = "Intermediate",
            reset = "53ec08",
            seq   = {
                {file="49801d", label="Down Q Loop"},
                {file="74adbe", label="Down P Loop"},
                {file="6d4483", label="Double Humpty"},
                {file="12a635", label="Loop"},
                {file="788a52", label="90 Roller"},
                {file="7a72d8", label="Humpty"},
                {file="5dc8d3", label="Hammerhead"},
                {file="d674a2", label="Immelmann"},
                {file="abcd26", label="Down Tear Drop"},
                {file="14f100", label="Reverse Cuban"},
            },
        },
        {
            key   = "ialt",
            name  = "Intermediate ALT",
            reset = "8f43d3",
            seq   = {
                {file="49801d", label="Down Q Loop"},
                {file="74adbe", label="Down P Loop"},
                {file="6d4483", label="Double Humpty"},
                {file="12a635", label="Loop"},
                {file="5dc8d3", label="Hammerhead"},
                {file="c46f96", label="Humpty"},
                {file="d674a2", label="Immelmann"},
                {file="abcd26", label="Down Tear Drop"},
                {file="14f100", label="Reverse Cuban"},
                {file="a7191c", label="Reversing Loop"},
            },
        },
        {
            key   = "advan",
            name  = "Advanced",
            reset = "7ccc94",
            seq   = {
                {file="6b79fc", label="Loop"},
                {file="662802", label="Tear Drop"},
                {file="d1e8b6", label="270 Roller"},
                {file="543ef4", label="Hammerhead"},
                {file="43475d", label="Reversing Loop"},
                {file="4d71fc", label="Lay Down Humpty"},
                {file="7c31f1", label="Immelmann"},
                {file="db1be6", label="Down Humpty"},
                {file="db0910", label="Vertical Down Line"},
                {file="63e99e", label="Humpty"},
            },
        },
        {
            key   = "aalt",
            name  = "Advanced ALT",
            reset = "699fed",
            seq   = {
                {file="6b79fc", label="Loop"},
                {file="662802", label="Tear Drop"},
                {file="7b0fe9", label="Half Reverse Cuban"},
                {file="543ef4", label="Hammerhead"},
                {file="43475d", label="Reversing Loop"},
                {file="4d71fc", label="Lay Down Humpty"},
                {file="7c31f1", label="Immelmann"},
                {file="324135", label="Down Humpty"},
                {file="d6995b", label="Vertical Down Line"},
                {file="5e3c3e", label="Humpty"},
            },
        },
        {
            key   = "unlim",
            name  = "Unlimited",
            reset = "379bd7",
            seq   = {
                {file="48017f", label="Down Q Loop"},
                {file="6612e8", label="Spin with Down Humpty"},
                {file="69aa05", label="Down Humpty"},
                {file="6151f8", label="Split S"},
                {file="f3324c", label="Hammerhead"},
                {file="07d57c", label="360 Roller"},
                {file="ffe578", label="Sharks Tooth"},
                {file="4003b7", label="P Loop"},
                {file="2cbb71", label="Humpty"},
                {file="f1699d", label="Lay Down Humpty"},
            },
        },
        {
            key   = "ualt",
            name  = "Unlimited ALT",
            reset = "5aefed",
            seq   = {
                {file="48017f", label="Down Q Loop"},
                {file="8ea8fa", label="1-1/2 Spin with Down Humpty"},
                {file="69aa05", label="Down Humpty"},
                {file="6151f8", label="Split S"},
                {file="f3324c", label="Hammerhead"},
                {file="d9f044", label="Loop"},
                {file="ffe578", label="Sharks Tooth"},
                {file="65160a", label="P Loop"},
                {file="a0ea55", label="Humpty"},
                {file="f1699d", label="Lay Down Humpty"},
            },
        },
    },
}
