return {
    year    = "2026",
    classes = {
        {
            key   = "basic",
            name  = "Basic",
            reset = "reset-basic-8f5c0bd2",
            seq   = {
                {file="loop-6c260463", label="Loop"},
                {file="reverse-half-cuban-efc78948", label="Reverse Half Cuban"},
                {file="roll-28432ff9", label="Roll"},
                {file="immelmann-a5bf0b3d", label="Immelmann"},
                {file="45-downline-9fdb799f", label="45 Downline"},
                {file="hammerhead-34648bf1", label="Hammerhead"},
                {file="humpty-bump-49898ee5", label="Humpty Bump"},
                {file="vertical-upline-d8766cad", label="Vertical Upline"},
                {file="down-sharks-tooth-spin-dea81b46", label="Down Sharks Tooth Spin"},
                {file="split-s-2457d785", label="Split S"},
            },
        },
        {
            key   = "sport",
            name  = "Sportsman",
            reset = "reset-sport-8b330e32",
            seq   = {
                {file="q-loop-8fb90c0b", label="Q Loop"},
                {file="bow-tie-a0d18cb9", label="Bow Tie"},
                {file="down-humpty-95e6a404", label="Down Humpty"},
                {file="split-s-47b40932", label="Split S"},
                {file="hammerhead-f3222b9a", label="Hammerhead"},
                {file="goldfish-632aaaa2", label="Goldfish"},
                {file="down-humpty-bump-c7629585", label="Down Humpty Bump"},
                {file="down-sharks-tooth-964556f5", label="Down Sharks Tooth"},
                {file="180-inverted-turn-fca74fc8", label="180 Inverted Turn"},
                {file="down-fig-n-0f13642e", label="Down Fig N"},
            },
        },
        {
            key   = "inter",
            name  = "Intermediate",
            reset = "reset-inter-7fef0d50",
            seq   = {
                {file="fig-n-bf2b0a3d", label="Fig N"},
                {file="laydown-humpty-1c72a6c9", label="Laydown Humpty"},
                {file="half-reverse-cuban-054bb707", label="Half Reverse Cuban"},
                {file="spin-6de9190c", label="Spin"},
                {file="hammerhead-91769321", label="Hammerhead"},
                {file="q-loop-cca0aa6d", label="Q Loop"},
                {file="double-humpty-d8156fd4", label="Double Humpty"},
                {file="vertical-down-line-f664794d", label="Vertical Down Line"},
                {file="reverse-laydown-humpty-9523f40a", label="Reverse Laydown Humpty"},
                {file="90-degree-roller-2c40ae38", label="90 Degree Roller"},
            },
        },
        {
            key   = "ialt",
            name  = "Intermediate ALT",
            reset = "reset-ialt-c8982ae3",
            seq   = {
                {file="fig-n-bf2b0a3d", label="Fig N"},
                {file="laydown-humpty-1c72a6c9", label="Laydown Humpty"},
                {file="half-reverse-cuban-054bb707", label="Half Reverse Cuban"},
                {file="spin-6de9190c", label="Spin"},
                {file="hammerhead-91769321", label="Hammerhead"},
                {file="q-loop-cca0aa6d", label="Q Loop"},
                {file="double-humpty-d8156fd4", label="Double Humpty"},
                {file="vertical-down-line-f664794d", label="Vertical Down Line"},
                {file="reverse-laydown-humpty-9523f40a", label="Reverse Laydown Humpty"},
                {file="half-cuban-85915bfc", label="Half Cuban"},
            },
        },
        {
            key   = "advan",
            name  = "Advanced",
            reset = "reset-advan-e7dc8744",
            seq   = {
                {file="fig-p-958a6404", label="Fig P"},
                {file="half-cuban-95ebc2d7", label="Half Cuban"},
                {file="loop-2c15cc05", label="Loop"},
                {file="hammerhead-4aca7f4d", label="Hammerhead"},
                {file="270-roller-711e718a", label="270 Roller"},
                {file="double-humpty-0399fb87", label="Double Humpty"},
                {file="half-reverse-cuban-1a7c4305", label="Half Reverse Cuban"},
                {file="spin-7bdc9e6b", label="Spin"},
                {file="tear-drop-46f78217", label="Tear Drop"},
                {file="sharks-tooth-c145242c", label="Sharks Tooth"},
            },
        },
        {
            key   = "aalt",
            name  = "Advanced ALT",
            reset = "reset-aalt-3c5da9f0",
            seq   = {
                {file="fig-p-958a6404", label="Fig P"},
                {file="half-cuban-95ebc2d7", label="Half Cuban"},
                {file="loop-2c15cc05", label="Loop"},
                {file="hammerhead-4aca7f4d", label="Hammerhead"},
                {file="p-loop-c6f4cf89", label="P Loop"},
                {file="double-humpty-0399fb87", label="Double Humpty"},
                {file="half-reverse-cuban-1a7c4305", label="Half Reverse Cuban"},
                {file="spin-7bdc9e6b", label="Spin"},
                {file="tear-drop-46f78217", label="Tear Drop"},
                {file="sharks-tooth-c145242c", label="Sharks Tooth"},
            },
        },
        {
            key   = "unlim",
            name  = "Unlimited",
            reset = "reset-unlim-71fc1a67",
            seq   = {
                {file="laydown-s-e5765e5a", label="Laydown S"},
                {file="hammerhead-1f1567df", label="Hammerhead"},
                {file="reverse-laydown-humpty-8b6a988d", label="Reverse Laydown Humpty"},
                {file="immelmann-2da1159a", label="Immelmann"},
                {file="down-loop-47ee27c9", label="Down Loop"},
                {file="spin-29d9456c", label="Spin"},
                {file="humpty-e1786de6", label="Humpty"},
                {file="sharks-tooth-cfbced3a", label="Sharks Tooth"},
                {file="tear-drop-be0af6f7", label="Tear Drop"},
                {file="270-degree-roller-751d8c67", label="270 Degree Roller"},
            },
        },
        {
            key   = "ualt",
            name  = "Unlimited ALT",
            reset = "reset-ualt-c024eaab",
            seq   = {
                {file="laydown-s-e5765e5a", label="Laydown S"},
                {file="hammerhead-1f1567df", label="Hammerhead"},
                {file="reverse-laydown-humpty-8b6a988d", label="Reverse Laydown Humpty"},
                {file="immelmann-2da1159a", label="Immelmann"},
                {file="down-loop-47ee27c9", label="Down Loop"},
                {file="spin-29d9456c", label="Spin"},
                {file="humpty-e1786de6", label="Humpty"},
                {file="sharks-tooth-cfbced3a", label="Sharks Tooth"},
                {file="tear-drop-606745cb", label="Tear Drop"},
                {file="half-reverse-cuban-31ff3d3a", label="Half Reverse Cuban"},
            },
        },
    },
}
