return {
    year    = "2026",
    classes = {
        {
            key   = "basic",
            name  = "Basic",
            reset = "2f7cd5",
            seq   = {
                {file="ceaecb", label="Loop"},
                {file="9a82e1", label="Reverse Half Cuban"},
                {file="e673a1", label="Roll"},
                {file="5e8b19", label="Immelmann"},
                {file="33df59", label="45 Downline"},
                {file="460043", label="Hammerhead"},
                {file="0e1c80", label="Humpty Bump"},
                {file="6bb17e", label="Vertical Upline"},
                {file="414026", label="Down Sharks Tooth Spin"},
                {file="20f5b2", label="Split S"},
            },
        },
        {
            key   = "sport",
            name  = "Sportsman",
            reset = "4afef4",
            seq   = {
                {file="f10f90", label="Q Loop"},
                {file="78b7e2", label="Bow Tie"},
                {file="7843ae", label="Down Humpty"},
                {file="4b1714", label="Split S"},
                {file="ae3462", label="Hammerhead"},
                {file="67a43e", label="Goldfish"},
                {file="ff8000", label="Down Humpty Bump"},
                {file="6410d4", label="Down Sharks Tooth"},
                {file="b165d2", label="180 Inverted Turn"},
                {file="3054df", label="Down Fig N"},
            },
        },
        {
            key   = "inter",
            name  = "Intermediate",
            reset = "53ec08",
            seq   = {
                {file="9e2926", label="Fig N"},
                {file="e32c7d", label="Laydown Humpty"},
                {file="4edc53", label="Half Reverse Cuban"},
                {file="0c04fe", label="Spin"},
                {file="6e38a2", label="Hammerhead"},
                {file="488b35", label="Q Loop"},
                {file="5afbfd", label="Double Humpty"},
                {file="7bf888", label="Vertical Down Line"},
                {file="16e65f", label="Reverse Laydown Humpty"},
                {file="118a7f", label="90 Degree Roller"},
            },
        },
        {
            key   = "ialt",
            name  = "Intermediate ALT",
            reset = "8f43d3",
            seq   = {
                {file="9e2926", label="Fig N"},
                {file="e32c7d", label="Laydown Humpty"},
                {file="4edc53", label="Half Reverse Cuban"},
                {file="0c04fe", label="Spin"},
                {file="6e38a2", label="Hammerhead"},
                {file="488b35", label="Q Loop"},
                {file="5afbfd", label="Double Humpty"},
                {file="7bf888", label="Vertical Down Line"},
                {file="16e65f", label="Reverse Laydown Humpty"},
                {file="881636", label="Half Cuban"},
            },
        },
        {
            key   = "advan",
            name  = "Advanced",
            reset = "7ccc94",
            seq   = {
                {file="2d2053", label="Fig P"},
                {file="a69a0f", label="Half Cuban"},
                {file="0a0edd", label="Loop"},
                {file="cb8782", label="Hammerhead"},
                {file="da0cb7", label="270 Roller"},
                {file="f0de7d", label="Double Humpty"},
                {file="bb63fb", label="Half Reverse Cuban"},
                {file="bb208c", label="Spin"},
                {file="0a07d0", label="Tear Drop"},
                {file="aa00eb", label="Sharks Tooth"},
            },
        },
        {
            key   = "aalt",
            name  = "Advanced ALT",
            reset = "699fed",
            seq   = {
                {file="2d2053", label="Fig P"},
                {file="a69a0f", label="Half Cuban"},
                {file="0a0edd", label="Loop"},
                {file="cb8782", label="Hammerhead"},
                {file="ded186", label="P Loop"},
                {file="f0de7d", label="Double Humpty"},
                {file="bb63fb", label="Half Reverse Cuban"},
                {file="bb208c", label="Spin"},
                {file="0a07d0", label="Tear Drop"},
                {file="aa00eb", label="Sharks Tooth"},
            },
        },
        {
            key   = "unlim",
            name  = "Unlimited",
            reset = "379bd7",
            seq   = {
                {file="3a61a0", label="Laydown S"},
                {file="af6f8e", label="Hammerhead"},
                {file="aa2c94", label="Reverse Laydown Humpty"},
                {file="df36d6", label="Immelmann"},
                {file="e14425", label="Down Loop"},
                {file="7cbea2", label="Spin"},
                {file="a9baf6", label="Humpty"},
                {file="c6f15a", label="Sharks Tooth"},
                {file="a7e703", label="Tear Drop"},
                {file="85ab47", label="270 Degree Roller"},
            },
        },
        {
            key   = "ualt",
            name  = "Unlimited ALT",
            reset = "5aefed",
            seq   = {
                {file="3a61a0", label="Laydown S"},
                {file="af6f8e", label="Hammerhead"},
                {file="aa2c94", label="Reverse Laydown Humpty"},
                {file="df36d6", label="Immelmann"},
                {file="e14425", label="Down Loop"},
                {file="7cbea2", label="Spin"},
                {file="a9baf6", label="Humpty"},
                {file="c6f15a", label="Sharks Tooth"},
                {file="e4b390", label="Tear Drop"},
                {file="75794b", label="Half Reverse Cuban"},
            },
        },
    },
}
