return {
    year    = "2026",
    classes = {
        {
            key  = "basic",
            name = "Basic",
            seq  = {
                {file="mnvr01", label="Loop"},
                {file="mnvr02", label="Reverse Half Cuban"},
                {file="mnvr03", label="Roll"},
                {file="mnvr04", label="Immelmann"},
                {file="mnvr05", label="45 Downline"},
                {file="mnvr06", label="Hammerhead"},
                {file="mnvr07", label="Humpty Bump"},
                {file="mnvr08", label="Vertical Upline"},
                {file="mnvr09", label="Down Sharks Tooth Spin"},
                {file="mnvr10", label="Split S"},
            },
        },
        {
            key  = "sport",
            name = "Sportsman",
            seq  = {
                {file="mnvr01", label="Q Loop"},
                {file="mnvr02", label="Bow Tie"},
                {file="mnvr03", label="Down Humpty"},
                {file="mnvr04", label="Split S"},
                {file="mnvr05", label="Hammerhead"},
                {file="mnvr06", label="Goldfish"},
                {file="mnvr07", label="Down Humpty Bump"},
                {file="mnvr08", label="Down Sharks Tooth"},
                {file="mnvr09", label="180 Inverted Turn"},
                {file="mnvr10", label="Down Fig N"},
            },
        },
        {
            key  = "inter",
            name = "Intermediate",
            seq  = {
                {file="mnvr01", label="Fig N"},
                {file="mnvr02", label="Laydown Humpty"},
                {file="mnvr03", label="Half Reverse Cuban"},
                {file="mnvr04", label="Spin"},
                {file="mnvr05", label="Hammerhead"},
                {file="mnvr06", label="Q Loop"},
                {file="mnvr07", label="Double Humpty"},
                {file="mnvr08", label="Vertical Down Line"},
                {file="mnvr09", label="Reverse Laydown Humpty"},
                {file="mnvr10", label="90 Degree Roller"},
            },
        },
        {
            key  = "ialt",
            name = "Intermediate ALT",
            seq  = {
                {file="mnvr01", label="Fig N"},
                {file="mnvr02", label="Laydown Humpty"},
                {file="mnvr03", label="Half Reverse Cuban"},
                {file="mnvr04", label="Spin"},
                {file="mnvr05", label="Hammerhead"},
                {file="mnvr06", label="Q Loop"},
                {file="mnvr07", label="Double Humpty"},
                {file="mnvr08", label="Vertical Down Line"},
                {file="mnvr09", label="Reverse Laydown Humpty"},
                {file="mnvr10", label="Half Cuban"},
            },
        },
        {
            key  = "advan",
            name = "Advanced",
            seq  = {
                {file="mnvr01", label="Fig P"},
                {file="mnvr02", label="Half Cuban"},
                {file="mnvr03", label="Loop"},
                {file="mnvr04", label="Hammerhead"},
                {file="mnvr05", label="270 Roller"},
                {file="mnvr06", label="Double Humpty"},
                {file="mnvr07", label="Half Reverse Cuban"},
                {file="mnvr08", label="Spin"},
                {file="mnvr09", label="Tear Drop"},
                {file="mnvr10", label="Sharks Tooth"},
            },
        },
        {
            key  = "aalt",
            name = "Advanced ALT",
            seq  = {
                {file="mnvr01", label="Fig P"},
                {file="mnvr02", label="Half Cuban"},
                {file="mnvr03", label="Loop"},
                {file="mnvr04", label="Hammerhead"},
                {file="mnvr05", label="P Loop"},
                {file="mnvr06", label="Double Humpty"},
                {file="mnvr07", label="Half Reverse Cuban"},
                {file="mnvr08", label="Spin"},
                {file="mnvr09", label="Tear Drop"},
                {file="mnvr10", label="Sharks Tooth"},
            },
        },
        {
            key  = "unlim",
            name = "Unlimited",
            seq  = {
                {file="mnvr01", label="Laydown S"},
                {file="mnvr02", label="Hammerhead"},
                {file="mnvr03", label="Reverse Laydown Humpty"},
                {file="mnvr04", label="Immelmann"},
                {file="mnvr05", label="Down Loop"},
                {file="mnvr06", label="Spin"},
                {file="mnvr07", label="Humpty"},
                {file="mnvr08", label="Sharks Tooth"},
                {file="mnvr09", label="Tear Drop"},
                {file="mnvr10", label="270 Degree Roller"},
            },
        },
        {
            key  = "ualt",
            name = "Unlimited ALT",
            seq  = {
                {file="mnvr01", label="Laydown S"},
                {file="mnvr02", label="Hammerhead"},
                {file="mnvr03", label="Reverse Laydown Humpty"},
                {file="mnvr04", label="Immelmann"},
                {file="mnvr05", label="Down Loop"},
                {file="mnvr06", label="Spin"},
                {file="mnvr07", label="Humpty"},
                {file="mnvr08", label="Sharks Tooth"},
                {file="mnvr09", label="Tear Drop"},
                {file="mnvr10", label="Half Reverse Cuban"},
            },
        },
    },
}
